### ISSUE TITLE
로그인된 사용자 처리 

### ISSUE THREAD

**Issue by so0choi** [zinirun/BlueCheck#14]
로그인 되어있는 사용자 어플 사용시 계속해서 로그인 되어있는 상태로 나옴. 로그인 시도 시 이미 세션 있는 상태라 /select로 넘어가면서 404 에러 발생

**Comment by zinirun** [comment]
`if(req.session.user)` part의 `else` 처리 리다이렉트 라우터를 `/select`에서 `/select/const`로 변경,
로그아웃 처리 전까지는 `/` 라우터로 접속 시 자동으로 공종 선택 라우터로 넘기도록 처리했습니다.
정상적으로 로그인 유저 처리되었습니다.

**Comment by zinirun** [comment]
`if(req.session.user)` part의 `else` 처리 리다이렉트 라우터를 `/select`에서 `/select/const`로 변경,
로그아웃 처리 전까지는 `/` 라우터로 접속 시 자동으로 공종 선택 라우터로 넘기도록 처리했습니다.
정상적으로 로그인 유저 처리되었습니다.
